import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    kotlin("jvm") version "1.9.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    // Use JUnit Jupiter for testing.
//    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    compileOnly("io.papermc.paper:paper-api:1.20.1-R0.1-SNAPSHOT")
//    implementation("org.apache.groovy:groovy-all:4.0.13")
// import scala 3
//    implementation("org.scala-lang:scala3-library_3:3.3.0")
}

application {
    // Define the main class for the application.
    mainClass.set("intelliractive.printer2.App")
}

//tasks.named<Test>("test") {
//    // Use JUnit Platform for unit tests.
//    useJUnitPlatform()
//}

//java {
//    toolchain.languageVersion.set(JavaLanguageVersion.of(19))
//}

// set jar manifest
tasks.withType<ShadowJar> {
    archiveFileName.set("printer2.jar")
//    destinationDirectory.set(file("C:\\Users\\Ilyushya\\Desktop\\goodplace2022\\gp-minigames\\printer\\plugins"))
    // запускать так: gradlew shadowJar -PdestDir= ...
}