/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intelliractive.printer2;

import org.bukkit.Bukkit;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.logging.Level;

public class App extends JavaPlugin implements Listener {
    /* public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    } */

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
        Bukkit.getPluginManager().registerEvents(new Game(this), this);
        getLogger().log(Level.FINE, "Game loaded!");
    }

//    @EventHandler
//    public void onPlayerJoin(PlayerJoinEvent event) {
//        event.getPlayer().sendMessage(Component.text("&aПривет, " + event.getPlayer().getName() + "!"));
//    }
}
